/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/free_realistic_disco_ball.glb 
Author: z o o z i    ( aka. zozo.surreal ) (https://sketchfab.com/zoozi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-realistic-disco-ball-f59e18c05c99406086dc1bffff07bafc
Title: Free Realistic Disco Ball
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/free_realistic_disco_ball.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="3a69432a4ae341e9838814cf38e58f0cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Disco_Sphere" position={[0, 900.28, 0]} rotation={[0, 0.482, 0]} scale={991.387}>
                  <group name="Base_Sphere" position={[0, -0.908, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.101}>
                    <mesh name="Base_Sphere_DiscoBall_0" geometry={nodes.Base_Sphere_DiscoBall_0.geometry} material={materials.DiscoBall} />
                  </group>
                  <group name="Reflective_Plates" position={[0, -0.908, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.101}>
                    <mesh name="Reflective_Plates_Reflective_0" geometry={nodes.Reflective_Plates_Reflective_0.geometry} material={materials.Reflective} />
                    <mesh name="Reflective_Plates_Reflective_0_1" geometry={nodes.Reflective_Plates_Reflective_0_1.geometry} material={materials.Reflective} />
                    <mesh name="Reflective_Plates_Reflective_0_2" geometry={nodes.Reflective_Plates_Reflective_0_2.geometry} material={materials.Reflective} />
                  </group>
                  <group name="Fix" position={[0, -0.908, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.101}>
                    <mesh name="Fix_Metal_0" geometry={nodes.Fix_Metal_0.geometry} material={materials.Metal} />
                  </group>
                  <group name="Chain" position={[0, -0.908, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.101}>
                    <mesh name="Chain_Metal_0" geometry={nodes.Chain_Metal_0.geometry} material={materials.Metal} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/free_realistic_disco_ball.glb')
